// Code generated by MockGen. DO NOT EDIT.
// Source: block_repository.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_block_repository.go -package=repository -source=block_repository.go
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/ryze/internal/domain/block/model"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockRepository is a mock of BlockRepository interface.
type MockBlockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlockRepositoryMockRecorder
	isgomock struct{}
}

// MockBlockRepositoryMockRecorder is the mock recorder for MockBlockRepository.
type MockBlockRepositoryMockRecorder struct {
	mock *MockBlockRepository
}

// NewMockBlockRepository creates a new mock instance.
func NewMockBlockRepository(ctrl *gomock.Controller) *MockBlockRepository {
	mock := &MockBlockRepository{ctrl: ctrl}
	mock.recorder = &MockBlockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockRepository) EXPECT() *MockBlockRepositoryMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockBlockRepository) FindByID(ctx context.Context, id string) (*model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBlockRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBlockRepository)(nil).FindByID), ctx, id)
}

// FindLatest mocks base method.
func (m *MockBlockRepository) FindLatest(ctx context.Context, limit int) ([]*model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatest", ctx, limit)
	ret0, _ := ret[0].([]*model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatest indicates an expected call of FindLatest.
func (mr *MockBlockRepositoryMockRecorder) FindLatest(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatest", reflect.TypeOf((*MockBlockRepository)(nil).FindLatest), ctx, limit)
}
