// Package scan Code generated by swaggo/swag. DO NOT EDIT
package scan

import "github.com/swaggo/swag"

const docTemplateblock_scan = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Sean Zheng",
            "url": "https://blog.seancheng.space",
            "email": "blackhorseya@gmail.com"
        },
        "license": {
            "name": "GPL-3.0",
            "url": "https://spdx.org/licenses/GPL-3.0-only.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfoblock_scan holds exported Swagger Info so clients can modify it
var SwaggerInfoblock_scan = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Ryze Block Scan API",
	Description:      "Ryze Block Scan API document.",
	InfoInstanceName: "block_scan",
	SwaggerTemplate:  docTemplateblock_scan,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfoblock_scan.InstanceName(), SwaggerInfoblock_scan)
}
