// Code generated by MockGen. DO NOT EDIT.
// Source: block_scanner.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_block_scanner.go -package=service -source=block_scanner.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/ryze/internal/domain/block/model"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockScanner is a mock of BlockScanner interface.
type MockBlockScanner struct {
	ctrl     *gomock.Controller
	recorder *MockBlockScannerMockRecorder
	isgomock struct{}
}

// MockBlockScannerMockRecorder is the mock recorder for MockBlockScanner.
type MockBlockScannerMockRecorder struct {
	mock *MockBlockScanner
}

// NewMockBlockScanner creates a new mock instance.
func NewMockBlockScanner(ctrl *gomock.Controller) *MockBlockScanner {
	mock := &MockBlockScanner{ctrl: ctrl}
	mock.recorder = &MockBlockScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockScanner) EXPECT() *MockBlockScannerMockRecorder {
	return m.recorder
}

// ScanBlocks mocks base method.
func (m *MockBlockScanner) ScanBlocks(c context.Context, blocks chan<- *model.Block, opts ...ScanBlockOption) error {
	m.ctrl.T.Helper()
	varargs := []any{c, blocks}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanBlocks", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanBlocks indicates an expected call of ScanBlocks.
func (mr *MockBlockScannerMockRecorder) ScanBlocks(c, blocks any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{c, blocks}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanBlocks", reflect.TypeOf((*MockBlockScanner)(nil).ScanBlocks), varargs...)
}
