// Code generated by MockGen. DO NOT EDIT.
// Source: account_repository.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_account_repository.go -package=repository -source=account_repository.go
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/ryze/internal/domain/account/model"
	model0 "github.com/blackhorseya/ryze/internal/domain/transaction/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAccountRepository is a mock of AccountRepository interface.
type MockAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockAccountRepositoryMockRecorder is the mock recorder for MockAccountRepository.
type MockAccountRepositoryMockRecorder struct {
	mock *MockAccountRepository
}

// NewMockAccountRepository creates a new mock instance.
func NewMockAccountRepository(ctrl *gomock.Controller) *MockAccountRepository {
	mock := &MockAccountRepository{ctrl: ctrl}
	mock.recorder = &MockAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountRepository) EXPECT() *MockAccountRepositoryMockRecorder {
	return m.recorder
}

// FindByAddress mocks base method.
func (m *MockAccountRepository) FindByAddress(c context.Context, address string) (*model.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAddress", c, address)
	ret0, _ := ret[0].(*model.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAddress indicates an expected call of FindByAddress.
func (mr *MockAccountRepositoryMockRecorder) FindByAddress(c, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAddress", reflect.TypeOf((*MockAccountRepository)(nil).FindByAddress), c, address)
}

// GetBalance mocks base method.
func (m *MockAccountRepository) GetBalance(c context.Context, address string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", c, address)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockAccountRepositoryMockRecorder) GetBalance(c, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockAccountRepository)(nil).GetBalance), c, address)
}

// GetTransactionHistory mocks base method.
func (m *MockAccountRepository) GetTransactionHistory(c context.Context, address string, limit int) ([]*model0.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionHistory", c, address, limit)
	ret0, _ := ret[0].([]*model0.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionHistory indicates an expected call of GetTransactionHistory.
func (mr *MockAccountRepositoryMockRecorder) GetTransactionHistory(c, address, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionHistory", reflect.TypeOf((*MockAccountRepository)(nil).GetTransactionHistory), c, address, limit)
}
