# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
#services:
#  server:
#    build:
#      context: .
#      target: final
#    ports:
#      - 30000:30000

services:
  platform:
    build:
      context: .
      target: final
    command:
      - --config=/app/configs/example.yaml
      - start
      - platform
    ports:
      - 50051:50051
    volumes:
      - ./configs/example.yaml:/app/configs/example.yaml
    depends_on:
      - mongodb
      - postgresql

  daemon:
    build:
      context: .
      target: final
    command:
      - --config=/app/configs/example.yaml
      - start
      - daemon
    volumes:
      - ./configs/example.yaml:/app/configs/example.yaml
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    volumes:
      - mongo-data:/data/db

  postgresql:
    image: postgres:14
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: ryze

volumes:
  mongo-data:
  pg-data: