// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package repo is a generated GoMock package.
package repo

import (
	reflect "reflect"

	contextx "github.com/blackhorseya/ryze/pkg/contextx"
	model "github.com/blackhorseya/ryze/pkg/entity/domain/block/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIRepo is a mock of IRepo interface.
type MockIRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRepoMockRecorder
}

// MockIRepoMockRecorder is the mock recorder for MockIRepo.
type MockIRepoMockRecorder struct {
	mock *MockIRepo
}

// NewMockIRepo creates a new mock instance.
func NewMockIRepo(ctrl *gomock.Controller) *MockIRepo {
	mock := &MockIRepo{ctrl: ctrl}
	mock.recorder = &MockIRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepo) EXPECT() *MockIRepoMockRecorder {
	return m.recorder
}

// GetBlockByHash mocks base method.
func (m *MockIRepo) GetBlockByHash(ctx contextx.Contextx, hash []byte) (*model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByHash", ctx, hash)
	ret0, _ := ret[0].(*model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHash indicates an expected call of GetBlockByHash.
func (mr *MockIRepoMockRecorder) GetBlockByHash(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHash", reflect.TypeOf((*MockIRepo)(nil).GetBlockByHash), ctx, hash)
}

// GetBlockByHeight mocks base method.
func (m *MockIRepo) GetBlockByHeight(ctx contextx.Contextx, height uint64) (*model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByHeight", ctx, height)
	ret0, _ := ret[0].(*model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByHeight indicates an expected call of GetBlockByHeight.
func (mr *MockIRepoMockRecorder) GetBlockByHeight(ctx, height interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByHeight", reflect.TypeOf((*MockIRepo)(nil).GetBlockByHeight), ctx, height)
}

// ListenNewBlock mocks base method.
func (m *MockIRepo) ListenNewBlock(ctx contextx.Contextx) (<-chan *model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenNewBlock", ctx)
	ret0, _ := ret[0].(<-chan *model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListenNewBlock indicates an expected call of ListenNewBlock.
func (mr *MockIRepoMockRecorder) ListenNewBlock(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenNewBlock", reflect.TypeOf((*MockIRepo)(nil).ListenNewBlock), ctx)
}
