// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func CreateTestRepo(o *EthOptions, rw *sqlx.DB) IRepo {
	iRepo := NewImpl(o, rw)
	return iRepo
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
