// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repo

import (
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/google/wire"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func CreateTestRepo(eht *ethclient.Client, rw *sqlx.DB) IRepo {
	iRepo := NewImpl(rw, eht)
	return iRepo
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
