// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	"github.com/blackhorseya/ryze/pkg/entity/domain/block/biz"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateBlockBiz() (biz.IBiz, error) {
	iBiz := NewImpl()
	return iBiz, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
