// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/ryze/internal/adapter/listener/block"
	"github.com/blackhorseya/ryze/internal/app/domain/block/biz"
	"github.com/blackhorseya/ryze/internal/app/domain/block/biz/repo"
	"github.com/blackhorseya/ryze/internal/pkg/config"
	"github.com/blackhorseya/ryze/internal/pkg/log"
	"github.com/blackhorseya/ryze/internal/pkg/storage/mariadb"
	"github.com/blackhorseya/ryze/internal/pkg/transports/kafkax"
	"github.com/blackhorseya/ryze/pkg/app"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateApplication serve caller to create application instance
func CreateApplication(path2 string) (app.Servicer, error) {
	configConfig := config.NewConfig(path2)
	logger, err := log.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	db, err := mariadb.NewMariadb(configConfig)
	if err != nil {
		return nil, err
	}
	client, err := repo.NewEthClient(configConfig, logger)
	if err != nil {
		return nil, err
	}
	migrate, err := mariadb.NewMigration(configConfig, db)
	if err != nil {
		return nil, err
	}
	writer, err := kafkax.NewWriter(configConfig)
	if err != nil {
		return nil, err
	}
	iRepo, err := repo.NewImpl(logger, db, client, migrate, writer)
	if err != nil {
		return nil, err
	}
	iBiz := biz.NewImpl(iRepo)
	listener := block.NewImpl(logger, iBiz)
	servicer, err := NewService(logger, listener)
	if err != nil {
		return nil, err
	}
	return servicer, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, log.ProviderSet, kafkax.WriterSet, mariadb.ProviderSet, block.ListenerSet, biz.BlockSet, repo.BlockSet, NewService)
