// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package scan

import (
	"github.com/blackhorseya/ryze/adpater/block/wirex"
	"github.com/blackhorseya/ryze/app/infra/configx"
	"github.com/blackhorseya/ryze/app/infra/transports/httpx"
	"github.com/blackhorseya/ryze/pkg/adapterx"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Restful, error) {
	configuration, err := configx.NewConfiguration(v)
	if err != nil {
		return nil, err
	}
	application, err := initApplication(configuration)
	if err != nil {
		return nil, err
	}
	injector := &wirex.Injector{
		C: configuration,
		A: application,
	}
	server, err := initServer(application)
	if err != nil {
		return nil, err
	}
	adapterxRestful := NewRestful(injector, server)
	return adapterxRestful, nil
}

// wire.go:

func initApplication(config *configx.Configuration) (*configx.Application, error) {
	return config.Services["block-scan"], nil
}

func initServer(app *configx.Application) (*httpx.Server, error) {
	return httpx.NewServer(app.HTTP)
}
