// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package scan

import (
	"errors"
	"fmt"
	"github.com/blackhorseya/ryze/adapter/block/wirex"
	"github.com/blackhorseya/ryze/app/domain/block/biz"
	"github.com/blackhorseya/ryze/app/infra/configx"
	"github.com/blackhorseya/ryze/app/infra/otelx"
	"github.com/blackhorseya/ryze/app/infra/transports/httpx"
	"github.com/blackhorseya/ryze/pkg/adapterx"
	"github.com/blackhorseya/ryze/pkg/contextx"
	"github.com/spf13/viper"
)

import (
	_ "github.com/blackhorseya/ryze/api/block/scan"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Restful, error) {
	configuration, err := configx.NewConfiguration(v)
	if err != nil {
		return nil, err
	}
	application, err := initApplication(configuration)
	if err != nil {
		return nil, err
	}
	blockServiceServer := biz.NewBlockService()
	injector := &wirex.Injector{
		C:            configuration,
		A:            application,
		BlockService: blockServiceServer,
	}
	server, err := initServer(application)
	if err != nil {
		return nil, err
	}
	adapterxRestful := NewRestful(injector, server)
	return adapterxRestful, nil
}

// wire.go:

func initApplication(config *configx.Configuration) (*configx.Application, error) {
	app, ok := config.Services["block-scan"]
	if !ok {
		return nil, errors.New("[block-scan] service not found")
	}

	err := otelx.SetupOTelSDK(contextx.Background(), app)
	if err != nil {
		return nil, fmt.Errorf("failed to setup OpenTelemetry SDK: %w", err)
	}

	return app, nil
}

func initServer(app *configx.Application) (*httpx.Server, error) {
	return httpx.NewServer(app.HTTP)
}
