// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_service.go -package=block -source=service.go
//

// Package block is a generated GoMock package.
package block

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/ryze/internal/domain/block/model"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetBlockByID mocks base method.
func (m *MockService) GetBlockByID(c context.Context, id string) (*model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockByID", c, id)
	ret0, _ := ret[0].(*model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBlockByID indicates an expected call of GetBlockByID.
func (mr *MockServiceMockRecorder) GetBlockByID(c, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockByID", reflect.TypeOf((*MockService)(nil).GetBlockByID), c, id)
}

// GetLatestBlocks mocks base method.
func (m *MockService) GetLatestBlocks(c context.Context, limit int) ([]*model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestBlocks", c, limit)
	ret0, _ := ret[0].([]*model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestBlocks indicates an expected call of GetLatestBlocks.
func (mr *MockServiceMockRecorder) GetLatestBlocks(c, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestBlocks", reflect.TypeOf((*MockService)(nil).GetLatestBlocks), c, limit)
}

// ScanBlock mocks base method.
func (m *MockService) ScanBlock(c context.Context, blocks chan<- *model.Block, opts ...ScanBlockOption) error {
	m.ctrl.T.Helper()
	varargs := []any{c, blocks}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ScanBlock", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScanBlock indicates an expected call of ScanBlock.
func (mr *MockServiceMockRecorder) ScanBlock(c, blocks any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{c, blocks}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScanBlock", reflect.TypeOf((*MockService)(nil).ScanBlock), varargs...)
}
