// Code generated by MockGen. DO NOT EDIT.
// Source: block.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_block.go -package=repo -source=block.go
//

// Package repo is a generated GoMock package.
package repo

import (
	reflect "reflect"

	model "github.com/blackhorseya/ryze/entity/domain/block/model"
	contextx "github.com/blackhorseya/ryze/pkg/contextx"
	gomock "go.uber.org/mock/gomock"
)

// MockIBlockRepo is a mock of IBlockRepo interface.
type MockIBlockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIBlockRepoMockRecorder
}

// MockIBlockRepoMockRecorder is the mock recorder for MockIBlockRepo.
type MockIBlockRepoMockRecorder struct {
	mock *MockIBlockRepo
}

// NewMockIBlockRepo creates a new mock instance.
func NewMockIBlockRepo(ctrl *gomock.Controller) *MockIBlockRepo {
	mock := &MockIBlockRepo{ctrl: ctrl}
	mock.recorder = &MockIBlockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBlockRepo) EXPECT() *MockIBlockRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIBlockRepo) Create(ctx contextx.Contextx, item *model.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIBlockRepoMockRecorder) Create(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIBlockRepo)(nil).Create), ctx, item)
}

// Delete mocks base method.
func (m *MockIBlockRepo) Delete(ctx contextx.Contextx, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIBlockRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIBlockRepo)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockIBlockRepo) GetByID(ctx contextx.Contextx, id string) (*model.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockIBlockRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockIBlockRepo)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockIBlockRepo) Update(ctx contextx.Contextx, item *model.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIBlockRepoMockRecorder) Update(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIBlockRepo)(nil).Update), ctx, item)
}
