// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/blackhorseya/ryze/internal/adapter/restful"
	"github.com/blackhorseya/ryze/internal/app/domain/block/biz"
	"github.com/blackhorseya/ryze/internal/app/domain/block/biz/repo"
	"github.com/blackhorseya/ryze/internal/pkg/config"
	"github.com/blackhorseya/ryze/internal/pkg/httpx"
	"github.com/blackhorseya/ryze/internal/pkg/log"
	"github.com/blackhorseya/ryze/internal/pkg/storage/mariadb"
	"github.com/blackhorseya/ryze/pkg/app"
	"github.com/google/wire"
)

// Injectors from wire.go:

// CreateApplication serve caller to create application instance
func CreateApplication(path2 string) (app.Servicer, error) {
	viper, err := config.NewConfig(path2)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(options)
	if err != nil {
		return nil, err
	}
	httpxOptions, err := httpx.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	engine := httpx.NewRouter(httpxOptions)
	server := httpx.NewServer(httpxOptions, logger, engine)
	mariadbOptions, err := mariadb.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	db, err := mariadb.NewMariadb(mariadbOptions)
	if err != nil {
		return nil, err
	}
	ethOptions, err := repo.NewEthOptions(viper, logger)
	if err != nil {
		return nil, err
	}
	client, err := repo.NewEthClient(ethOptions, logger)
	if err != nil {
		return nil, err
	}
	migrate, err := mariadb.NewMigration(mariadbOptions, db)
	if err != nil {
		return nil, err
	}
	iRepo, err := repo.NewImpl(logger, db, client, migrate)
	if err != nil {
		return nil, err
	}
	iBiz := biz.NewImpl(iRepo)
	adapterRestful := restful.NewImpl(logger, engine, iBiz)
	servicer, err := NewService(logger, server, adapterRestful)
	if err != nil {
		return nil, err
	}
	return servicer, nil
}

// wire.go:

var providerSet = wire.NewSet(config.ProviderSet, log.ProviderSet, httpx.ServerSet, mariadb.ProviderSet, restful.ProviderSet, biz.BlockSet, repo.BlockSet, NewService)
