log:
  level: debug
  format: console

services:
  platform-grpc:
    name: dev-platform-grpc

    grpc:
      url: localhost
      port: 50051

    storage:
      mongodb:
        dsn: mongodb://admin:changeme@mongodb/?retryWrites=true&w=majority

      postgresql:
        dsn: "user=root password=changeme dbname=ryze host=postgresql port=5432 sslmode=disable"

  block-grpc:
    name: dev-block-grpc

    grpc:
      port: 1992

    storage:
      mongodb:
        dsn: mongodb://admin:changeme@mongodb/?retryWrites=true&w=majority

networks:
  ton:
    name: ton
    testnet: false
