log:
  level: debug
  format: console

services:
  block-scan:
    name: dev-block-scan

  block-grpc:
    name: dev-block-grpc

    grpc:
      port: 1993

    storage:
      mongodb:
        dsn: mongodb://admin:changeme@mongodb/?retryWrites=true&w=majority

networks:
  ton:
    name: ton
    testnet: false
