log:
  level: debug
  format: console

services:
  block-grpc:
    name: example-block-grpc

    grpc:
      port: 1993

    otel:
      target: "localhost:4317"

networks:
  ton:
    name: ton
    testnet: false
