// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package daemon

import (
	"github.com/blackhorseya/ryze/pkg/adapterx"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Server, func(), error) {
	server, cleanup, err := NewServer()
	if err != nil {
		return nil, nil, err
	}
	return server, func() {
		cleanup()
	}, nil
}
