// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package daemon

import (
	"fmt"
	"github.com/blackhorseya/ryze/internal/infra/datasource/ton"
	"github.com/blackhorseya/ryze/internal/infra/stub"
	"github.com/blackhorseya/ryze/internal/service/block"
	"github.com/blackhorseya/ryze/internal/shared/configx"
	"github.com/blackhorseya/ryze/internal/shared/messaging"
	"github.com/blackhorseya/ryze/internal/shared/otelx"
	"github.com/blackhorseya/ryze/internal/shared/tonx"
	"github.com/blackhorseya/ryze/pkg/adapterx"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func New(v *viper.Viper) (adapterx.Server, func(), error) {
	configuration, err := configx.NewConfiguration(v)
	if err != nil {
		return nil, nil, err
	}
	application, err := InitApplication(configuration)
	if err != nil {
		return nil, nil, err
	}
	sdk, cleanup, err := otelx.SetupSDK(application)
	if err != nil {
		return nil, nil, err
	}
	blockRepository := stub.NewInMemoryBlockRepository()
	client, err := InitTonClient(configuration)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	blockAdapterImpl := ton.NewBlockAdapterImpl(client)
	service := block.NewService(blockRepository, blockAdapterImpl)
	injector := &Injector{
		C:        configuration,
		A:        application,
		OTelx:    sdk,
		BlockSvc: service,
	}
	eventBus := messaging.NewInMemoryEventBus()
	server, cleanup2, err := NewServer(injector, eventBus)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

const serviceName = "daemon"

// InitApplication is a function to initialize application.
func InitApplication(config *configx.Configuration) (*configx.Application, error) {
	return config.GetService(serviceName)
}

// InitTonClient is used to initialize the ton client.
func InitTonClient(config *configx.Configuration) (*tonx.Client, error) {
	settings, ok := config.Networks["ton"]
	if !ok {
		return nil, fmt.Errorf("network [ton] not found")
	}

	n := "mainnet"
	if settings.Testnet {
		n = "testnet"
	}

	return tonx.NewClient(tonx.Options{Network: n})
}
