// Code generated by MockGen. DO NOT EDIT.
// Source: network_repository.go
//
// Generated by this command:
//
//	mockgen -destination=./mock_network_repository.go -package=repository -source=network_repository.go
//

// Package repository is a generated GoMock package.
package repository

import (
	context "context"
	reflect "reflect"

	model "github.com/blackhorseya/ryze/internal/domain/network/model"
	gomock "go.uber.org/mock/gomock"
)

// MockNetworkRepository is a mock of NetworkRepository interface.
type MockNetworkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkRepositoryMockRecorder
	isgomock struct{}
}

// MockNetworkRepositoryMockRecorder is the mock recorder for MockNetworkRepository.
type MockNetworkRepositoryMockRecorder struct {
	mock *MockNetworkRepository
}

// NewMockNetworkRepository creates a new mock instance.
func NewMockNetworkRepository(ctrl *gomock.Controller) *MockNetworkRepository {
	mock := &MockNetworkRepository{ctrl: ctrl}
	mock.recorder = &MockNetworkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkRepository) EXPECT() *MockNetworkRepositoryMockRecorder {
	return m.recorder
}

// GetAllNodes mocks base method.
func (m *MockNetworkRepository) GetAllNodes(c context.Context) ([]*model.NodeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllNodes", c)
	ret0, _ := ret[0].([]*model.NodeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllNodes indicates an expected call of GetAllNodes.
func (mr *MockNetworkRepositoryMockRecorder) GetAllNodes(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllNodes", reflect.TypeOf((*MockNetworkRepository)(nil).GetAllNodes), c)
}

// GetNodeStatus mocks base method.
func (m *MockNetworkRepository) GetNodeStatus(c context.Context, nodeID string) (*model.NodeStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeStatus", c, nodeID)
	ret0, _ := ret[0].(*model.NodeStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeStatus indicates an expected call of GetNodeStatus.
func (mr *MockNetworkRepositoryMockRecorder) GetNodeStatus(c, nodeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeStatus", reflect.TypeOf((*MockNetworkRepository)(nil).GetNodeStatus), c, nodeID)
}

// GetStats mocks base method.
func (m *MockNetworkRepository) GetStats(c context.Context) (*model.NetworkStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", c)
	ret0, _ := ret[0].(*model.NetworkStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockNetworkRepositoryMockRecorder) GetStats(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockNetworkRepository)(nil).GetStats), c)
}
